### ISSUE TITLE
Alternative communication channel

### ISSUE THREAD

**Issue by chri2** [OpenIPC/website#33]
Telegram is probably a fine platform, but I do not use it nor any other platform requiring a phone number to register.

Yes, there are some ways around using my own phone number, but how much time and energy am I supposed to invest to talk to you nice people providing and using this project?

Any other technology not wanting my phone number and easy to register like irc, matrix, a forum, xmpp, github discussions would be very welcome.

**Comment by themactep** [comment]
Let's boil technicalities down to the simple issue - your personal choice not to use your phone number for a simple thing like authentication of an account. Is it an issue of OpenIPC? Hardly.

Telegram is a decent platform and I don't think you have enough arguments in your sleeve to convince all of us to move our conversation to some othere place where you would feel comfortable. Grow up man, this world is not spinning around you.

**Comment by chri2** [comment]
I didn't intend to ask anybody to leave telegram or change there communication channel. I just asked for an alternative place to communicate beside the dev-email-address and telegram. No need to get personal.

I appreciate a lot what you seem to accomplish here and am sorry if I asked an inappropriate question.

**Comment by themactep** [comment]
You are free to start a communication channel about OpenIPC using any social means you like. But the problem is that the communication involves at least two parties, and the core developers use Telegram. You may be able to invite a handful of users to the new media, but will you get the same quality of conversation as when people who know all the nuts and bolts of the firmware are also there? We are not a commercial project, we are not trying to cover all the bases and reach as many people as possible to sell crap. We do not have budget or people to abuse online presence with fingers in all bowls. We are enthusiasts who work on the project in our spare time and communicate where it is efficient and helpful for the cause. Telegram is the perfect platform for this. If for some reason you do not find this acceptable, maybe this project is not important enough for you.
